### ISSUE TITLE
Aria roles for the accordion style of multiblock - accessibility issue

### ISSUE THREAD

**Issue by james-pearce-bath-ac** [catalyst/moodle-block_multiblock#81]
The multiblock accordion tabs have the role=”radio”. This could be confusing to a screenreader user. A better aria role might be "tab".

**Comment by michaelkotlyar** [comment]
Totally agree with removing the radio role there. Looking at the examples below, it might not be necessary to have a role at all since the element is already a button.

https://getbootstrap.com/docs/4.6/components/collapse/#accordion-example
https://www.w3.org/WAI/ARIA/apg/example-index/accordion/accordion.html

**Comment by michaelkotlyar** [comment]
Finally got around to creating a [PR](https://github.com/catalyst/moodle-block_multiblock/pull/90) for this

**Comment by danmarsden** [comment]
fixed in #90

**Comment by danmarsden** [comment]
reverted that and set it to use role="tab" as the mustache validation failed when we removed the role completely. - thanks!
